import re

text = """3M Company (MMM)
AFLAC Inc. (AFL)
AbbVie Inc. (ABBV)
Abbott Laboratories (ABT)
Air Products & Chemicals Inc (APD)
A.O. Smith (AOS)
Archer-Daniels-Midland Co (ADM)
AT&T (T)
Automatic Data Processing (ADP)
Becton Dickinson (BDX)
Cardinal Health Inc. (CAH)
Chevron Corp. (CVX)
Cincinnati Financial Corp (CINF)
Cintas Corp (CTAS)
The Clorox Company (CLX)
Coca-Cola Co (KO)
Colgate-Palmolive (CL)
Consolidated Edison Inc (ED)
Dover Corp (DOV)
Ecolab Inc (ECL)
Emerson Electric (EMR)
Exxon Mobil Corp (XOM)
Federal Realty Investment Trust (FRT)
Franklin Resources (BEN)
General Dynamics (GD)
Genuine Parts Company (GPC)
W. W. Grainger (GWW)
Hormel Foods Corp (HRL)
Illinois Tool Works (ITW)
Johnson & Johnson (JNJ)
Kimberly-Clark (KMB)
Leggett & Platt (LEG)
Lowe's Companies, Inc. (LOW)
McCormick & Company (MKC)
McDonald's (MCD)
Medtronic (MDT)
Nucor (NUE)
PPG Industries (PPG)
PepsiCo (PEP)
Pentair (PNR)
Praxair (PX)
Procter & Gamble (PG)
Roper Technologies (ROP)
S&P Global (SPGI)
Sherwin-Williams (SHW)
Stanley Black & Decker Inc. (SWK)
Sysco (SYY)
T. Rowe Price (TROW)
Target Corporation (TGT)
VF Corporation (VFC)
Walmart (WMT)
Walgreen Boots Alliance (WBA)"""

stocks = re.findall('\((.*?)\)',text)

print(stocks)


